name: 'PASTA Threat Model Generator'
description: 'Auto-generate PASTA threat models from repository analysis'
author: 'cybrking'

branding:
  icon: 'shield'
  color: 'red'

inputs:
  anthropic-api-key:
    description: 'Anthropic API key for Claude-powered analysis'
    required: true

  config-path:
    description: 'Path to optional .threat-model.yml config'
    required: false
    default: '.threat-model.yml'

  output-formats:
    description: 'Output formats (markdown,json,html,pdf)'
    required: false
    default: 'markdown,json,html'

  fail-on-high-risk:
    description: 'Fail build if critical-risk vulnerabilities found'
    required: false
    default: 'false'

  github-token:
    description: 'GitHub token for creating issues and PRs'
    required: false

  create-issues:
    description: 'Create GitHub issues for medium/low findings'
    default: 'false'

  auto-fix:
    description: 'Generate AI fix PRs for critical/immediate findings'
    default: 'false'

  pr-severity:
    description: 'Comma-separated severity levels that get fix PRs when auto-fix is enabled (e.g., critical,high,medium)'
    default: 'critical,high'

outputs:
  threats-found:
    description: 'Total vulnerabilities identified'
  high-risk-count:
    description: 'Critical-risk vulnerabilities'
  report-path:
    description: 'Path to generated report'
  issues-created:
    description: 'Number of issues created'
  prs-created:
    description: 'Number of fix PRs created'

runs:
  using: 'node20'
  main: 'dist/index.js'
