name: 'PASTA Threat Model Generator'
description: 'Auto-generate PASTA threat models from repository analysis'
author: 'cybrking'

branding:
  icon: 'shield'
  color: 'red'

inputs:
  anthropic-api-key:
    description: 'Anthropic API key for Claude-powered analysis'
    required: true

  config-path:
    description: 'Path to optional .threat-model.yml config'
    required: false
    default: '.threat-model.yml'

  output-formats:
    description: 'Output formats (markdown,json)'
    required: false
    default: 'markdown,json'

  fail-on-high-risk:
    description: 'Fail build if critical-risk vulnerabilities found'
    required: false
    default: 'false'

outputs:
  threats-found:
    description: 'Total vulnerabilities identified'
  high-risk-count:
    description: 'Critical-risk vulnerabilities'
  report-path:
    description: 'Path to generated report'

runs:
  using: 'node20'
  main: 'dist/index.js'
